{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d2490b39",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "Apex Motion — Diseño y desarrollo web\n",
    "--------------------------------------\n",
    "Aplicación Streamlit de una sola página para presentar los planes de\n",
    "servicio de Apex Motion y generar una cotización lista para enviar por\n",
    "WhatsApp con un solo clic.\n",
    "\n",
    "Ejecutar con:\n",
    "    streamlit run app.py\n",
    "\"\"\"\n",
    "\n",
    "import urllib.parse\n",
    "\n",
    "import streamlit as st\n",
    "\n",
    "# =============================================================================\n",
    "# CAMBIA AQUÍ TUS DATOS DE CONTACTO Y SERVICIO\n",
    "# =============================================================================\n",
    "COMPANY_NAME = \"Apex Motion\"\n",
    "COMPANY_TAGLINE = \"Diseñamos y construimos el sitio web que tu negocio necesita para vender más.\"\n",
    "\n",
    "WHATSAPP_NUMBER = \"50259839777\"  # Formato internacional, solo dígitos, sin \"+\"\n",
    "\n",
    "DELIVERY_TIME = \"3 a 7 días hábiles\"\n",
    "BUSINESS_HOURS = \"Lunes a Viernes de 7:00 a 20:00\"\n",
    "\n",
    "CURRENCY = \"Q\"  # Símbolo de moneda usado en toda la página (Quetzales)\n",
    "\n",
    "# --- PLANES / PRECIOS -------------------------------------------------------\n",
    "# id:        identificador único (sin espacios) usado internamente\n",
    "# name:      nombre visible del plan\n",
    "# tagline:   una línea corta describiendo para quién es el plan\n",
    "# price:     precio del plan en números (sin símbolo de moneda)\n",
    "# featured:  True para destacar el plan como \"Más elegido\"\n",
    "# features:  lista de características que se muestran como checklist\n",
    "PLANS = [\n",
    "    {\n",
    "        \"id\": \"emprendedor\",\n",
    "        \"name\": \"Web Emprendedor\",\n",
    "        \"tagline\": \"Ideal para empezar con una presencia online simple y directa.\",\n",
    "        \"price\": 1200,\n",
    "        \"featured\": False,\n",
    "        \"features\": [\n",
    "            \"Landing page de una sola página\",\n",
    "            \"Diseño responsivo (móvil, tablet, escritorio)\",\n",
    "            \"Botón directo a WhatsApp\",\n",
    "        ],\n",
    "    },\n",
    "    {\n",
    "        \"id\": \"profesional\",\n",
    "        \"name\": \"Web Profesional\",\n",
    "        \"tagline\": \"El plan más elegido: un sitio completo para tu negocio.\",\n",
    "        \"price\": 1500,\n",
    "        \"featured\": True,\n",
    "        \"features\": [\n",
    "            \"Sitio completo de hasta 5 secciones\",\n",
    "            \"Optimización SEO básica\",\n",
    "            \"Integración con redes sociales\",\n",
    "        ],\n",
    "    },\n",
    "    {\n",
    "        \"id\": \"ecommerce\",\n",
    "        \"name\": \"Tienda Online / E-commerce\",\n",
    "        \"tagline\": \"Para vender tus productos directamente desde tu sitio.\",\n",
    "        \"price\": 3000,\n",
    "        \"featured\": False,\n",
    "        \"features\": [\n",
    "            \"Catálogo de productos\",\n",
    "            \"Pasarela de pagos integrada\",\n",
    "            \"Panel de administración\",\n",
    "        ],\n",
    "    },\n",
    "]\n",
    "\n",
    "# =============================================================================\n",
    "# CONFIGURACIÓN DE LA PÁGINA\n",
    "# =============================================================================\n",
    "st.set_page_config(\n",
    "    page_title=f\"{COMPANY_NAME} — Diseño y desarrollo web\",\n",
    "    page_icon=\"🚀\",\n",
    "    layout=\"wide\",\n",
    ")\n",
    "\n",
    "# =============================================================================\n",
    "# ESTILOS (paleta oficial de Apex Motion)\n",
    "# =============================================================================\n",
    "st.markdown(\n",
    "    \"\"\"\n",
    "    <style>\n",
    "    :root{\n",
    "        --primary-color:   #000000;   /* Fondo principal / texto */\n",
    "        --bg-color:        #001219;   /* Fondo general de la página */\n",
    "        --secondary-color: #14213d;   /* Tarjetas y contenedores */\n",
    "        --accent-color:    #0a9396;   /* Botones y destacados */\n",
    "        --accent-color-dark: #07686a;\n",
    "        --text-strong: #ffffff;\n",
    "        --text-soft:   #e5e5e5;\n",
    "    }\n",
    "\n",
    "    /* Fondo general de la app */\n",
    "    .stApp{\n",
    "        background-color: var(--bg-color);\n",
    "        color: var(--text-strong);\n",
    "    }\n",
    "\n",
    "    /* Asegurar texto legible en blanco/gris claro sobre fondo oscuro */\n",
    "    h1, h2, h3, h4, h5, h6, p, span, label, li, div{\n",
    "        color: var(--text-strong);\n",
    "    }\n",
    "    .subtle-text{ color: var(--text-soft) !important; }\n",
    "\n",
    "    /* Header */\n",
    "    .am-header{\n",
    "        text-align: center;\n",
    "        padding: 2.2rem 1rem 1.4rem 1rem;\n",
    "    }\n",
    "    .am-header h1{\n",
    "        font-size: 2.8rem;\n",
    "        font-weight: 800;\n",
    "        margin-bottom: 0.4rem;\n",
    "        letter-spacing: -0.01em;\n",
    "    }\n",
    "    .am-header h1 span{ color: var(--accent-color); }\n",
    "    .am-header p{\n",
    "        font-size: 1.15rem;\n",
    "        color: var(--text-soft) !important;\n",
    "        max-width: 640px;\n",
    "        margin: 0 auto;\n",
    "    }\n",
    "\n",
    "    /* Tarjetas informativas (entrega / horario) */\n",
    "    .info-card{\n",
    "        background-color: var(--secondary-color);\n",
    "        border: 1px solid rgba(255,255,255,0.12);\n",
    "        border-radius: 14px;\n",
    "        padding: 1.1rem 1.3rem;\n",
    "        text-align: center;\n",
    "        height: 100%;\n",
    "    }\n",
    "    .info-card .info-label{\n",
    "        font-size: 0.8rem;\n",
    "        text-transform: uppercase;\n",
    "        letter-spacing: .06em;\n",
    "        color: var(--accent-color) !important;\n",
    "        font-weight: 700;\n",
    "        margin-bottom: 0.35rem;\n",
    "    }\n",
    "    .info-card .info-value{\n",
    "        font-size: 1.05rem;\n",
    "        font-weight: 600;\n",
    "        color: var(--text-strong) !important;\n",
    "    }\n",
    "\n",
    "    /* Tarjetas de planes */\n",
    "    .plan-card{\n",
    "        background-color: var(--secondary-color);\n",
    "        border: 1px solid rgba(255,255,255,0.12);\n",
    "        border-radius: 18px;\n",
    "        padding: 1.6rem 1.4rem;\n",
    "        height: 100%;\n",
    "        display: flex;\n",
    "        flex-direction: column;\n",
    "        position: relative;\n",
    "    }\n",
    "    .plan-card.featured{\n",
    "        border: 1.5px solid var(--accent-color);\n",
    "        box-shadow: 0 0 0 3px rgba(10,147,150,0.18);\n",
    "    }\n",
    "    .plan-badge{\n",
    "        display: inline-block;\n",
    "        background-color: var(--accent-color);\n",
    "        color: #ffffff;\n",
    "        font-size: 0.72rem;\n",
    "        font-weight: 700;\n",
    "        padding: 0.25rem 0.7rem;\n",
    "        border-radius: 999px;\n",
    "        margin-bottom: 0.7rem;\n",
    "        width: fit-content;\n",
    "    }\n",
    "    .plan-name{\n",
    "        font-size: 1.3rem;\n",
    "        font-weight: 700;\n",
    "        margin-bottom: 0.3rem;\n",
    "        color: var(--text-strong) !important;\n",
    "    }\n",
    "    .plan-tagline{\n",
    "        font-size: 0.92rem;\n",
    "        color: var(--text-soft) !important;\n",
    "        min-height: 42px;\n",
    "        margin-bottom: 0.8rem;\n",
    "    }\n",
    "    .plan-price{\n",
    "        font-size: 2.1rem;\n",
    "        font-weight: 800;\n",
    "        color: var(--accent-color) !important;\n",
    "        margin-bottom: 0.9rem;\n",
    "    }\n",
    "    .plan-price span{\n",
    "        font-size: 0.95rem;\n",
    "        font-weight: 500;\n",
    "        color: var(--text-soft) !important;\n",
    "    }\n",
    "    .plan-features{\n",
    "        list-style: none;\n",
    "        padding-left: 0;\n",
    "        margin-bottom: 0.5rem;\n",
    "        flex-grow: 1;\n",
    "    }\n",
    "    .plan-features li{\n",
    "        font-size: 0.92rem;\n",
    "        color: var(--text-soft) !important;\n",
    "        padding: 0.3rem 0;\n",
    "        padding-left: 1.4rem;\n",
    "        position: relative;\n",
    "    }\n",
    "    .plan-features li::before{\n",
    "        content: \"✓\";\n",
    "        position: absolute;\n",
    "        left: 0;\n",
    "        color: var(--accent-color);\n",
    "        font-weight: 700;\n",
    "    }\n",
    "\n",
    "    /* Radio buttons de selección de plan: los agrandamos un poco */\n",
    "    div[role=\"radiogroup\"] label{\n",
    "        font-size: 1rem !important;\n",
    "        font-weight: 600 !important;\n",
    "    }\n",
    "\n",
    "    /* Botones generales de Streamlit */\n",
    "    .stButton > button{\n",
    "        background-color: var(--accent-color);\n",
    "        color: #ffffff;\n",
    "        border: none;\n",
    "        border-radius: 8px;\n",
    "        padding: 0.6rem 1.4rem;\n",
    "        font-weight: 700;\n",
    "        width: 100%;\n",
    "        transition: background-color .15s ease, transform .15s ease;\n",
    "    }\n",
    "    .stButton > button:hover{\n",
    "        background-color: var(--accent-color-dark);\n",
    "        color: #ffffff;\n",
    "        transform: translateY(-1px);\n",
    "    }\n",
    "\n",
    "    /* Botón de enlace (WhatsApp) */\n",
    "    .stLinkButton > a{\n",
    "        background-color: var(--accent-color) !important;\n",
    "        color: #ffffff !important;\n",
    "        border: none !important;\n",
    "        border-radius: 8px !important;\n",
    "        font-weight: 700 !important;\n",
    "        width: 100%;\n",
    "        text-align: center;\n",
    "        transition: background-color .15s ease, transform .15s ease;\n",
    "    }\n",
    "    .stLinkButton > a:hover{\n",
    "        background-color: var(--accent-color-dark) !important;\n",
    "        transform: translateY(-1px);\n",
    "    }\n",
    "\n",
    "    /* Resumen de cotización */\n",
    "    .quote-box{\n",
    "        background-color: var(--primary-color);\n",
    "        border: 1px solid rgba(255,255,255,0.14);\n",
    "        border-radius: 16px;\n",
    "        padding: 1.6rem;\n",
    "        margin-top: 1rem;\n",
    "    }\n",
    "    .quote-box h3{\n",
    "        color: var(--text-strong) !important;\n",
    "        margin-bottom: 0.6rem;\n",
    "    }\n",
    "    .quote-total{\n",
    "        font-size: 2rem;\n",
    "        font-weight: 800;\n",
    "        color: var(--accent-color) !important;\n",
    "        margin: 0.6rem 0 1rem 0;\n",
    "    }\n",
    "\n",
    "    /* Inputs de texto */\n",
    "    .stTextInput input, .stTextArea textarea{\n",
    "        background-color: var(--secondary-color) !important;\n",
    "        color: var(--text-strong) !important;\n",
    "        border: 1px solid rgba(255,255,255,0.18) !important;\n",
    "        border-radius: 8px !important;\n",
    "    }\n",
    "    .stTextInput input::placeholder, .stTextArea textarea::placeholder{\n",
    "        color: rgba(229,229,229,0.55) !important;\n",
    "    }\n",
    "    label{ color: var(--text-soft) !important; }\n",
    "\n",
    "    hr{ border-color: rgba(255,255,255,0.12) !important; }\n",
    "\n",
    "    footer, #MainMenu{ visibility: hidden; }\n",
    "    .am-footer{\n",
    "        text-align: center;\n",
    "        color: rgba(229,229,229,0.55) !important;\n",
    "        font-size: 0.85rem;\n",
    "        padding: 2rem 0 1rem 0;\n",
    "    }\n",
    "    </style>\n",
    "    \"\"\",\n",
    "    unsafe_allow_html=True,\n",
    ")\n",
    "\n",
    "# =============================================================================\n",
    "# ENCABEZADO\n",
    "# =============================================================================\n",
    "st.markdown(\n",
    "    f\"\"\"\n",
    "    <div class=\"am-header\">\n",
    "        <h1><span>{COMPANY_NAME}</span></h1>\n",
    "        <p>{COMPANY_TAGLINE}</p>\n",
    "    </div>\n",
    "    \"\"\",\n",
    "    unsafe_allow_html=True,\n",
    ")\n",
    "\n",
    "# =============================================================================\n",
    "# INFORMACIÓN DE SERVICIO Y GARANTÍA\n",
    "# =============================================================================\n",
    "info_col1, info_col2 = st.columns(2)\n",
    "with info_col1:\n",
    "    st.markdown(\n",
    "        f\"\"\"\n",
    "        <div class=\"info-card\">\n",
    "            <div class=\"info-label\">Tiempo de entrega</div>\n",
    "            <div class=\"info-value\">{DELIVERY_TIME}</div>\n",
    "        </div>\n",
    "        \"\"\",\n",
    "        unsafe_allow_html=True,\n",
    "    )\n",
    "with info_col2:\n",
    "    st.markdown(\n",
    "        f\"\"\"\n",
    "        <div class=\"info-card\">\n",
    "            <div class=\"info-label\">Horario de atención</div>\n",
    "            <div class=\"info-value\">{BUSINESS_HOURS}</div>\n",
    "        </div>\n",
    "        \"\"\",\n",
    "        unsafe_allow_html=True,\n",
    "    )\n",
    "\n",
    "st.markdown(\"<br>\", unsafe_allow_html=True)\n",
    "\n",
    "# =============================================================================\n",
    "# SECCIÓN DE PLANES\n",
    "# =============================================================================\n",
    "st.markdown(\"## Nuestros planes\")\n",
    "st.markdown(\n",
    "    '<p class=\"subtle-text\">Elige el plan que mejor se adapte a tu negocio. '\n",
    "    'El precio mostrado es el total del proyecto, sin costos adicionales.</p>',\n",
    "    unsafe_allow_html=True,\n",
    ")\n",
    "st.markdown(\"<br>\", unsafe_allow_html=True)\n",
    "\n",
    "plan_cols = st.columns(3)\n",
    "for col, plan in zip(plan_cols, PLANS):\n",
    "    with col:\n",
    "        featured_class = \"plan-card featured\" if plan[\"featured\"] else \"plan-card\"\n",
    "        badge_html = '<div class=\"plan-badge\">Más elegido</div>' if plan[\"featured\"] else \"\"\n",
    "        features_html = \"\".join(f\"<li>{feature}</li>\" for feature in plan[\"features\"])\n",
    "\n",
    "        st.markdown(\n",
    "            f\"\"\"\n",
    "            <div class=\"{featured_class}\">\n",
    "                {badge_html}\n",
    "                <div class=\"plan-name\">{plan['name']}</div>\n",
    "                <div class=\"plan-tagline\">{plan['tagline']}</div>\n",
    "                <div class=\"plan-price\">{CURRENCY}{plan['price']:,}<span> / proyecto</span></div>\n",
    "                <ul class=\"plan-features\">{features_html}</ul>\n",
    "            </div>\n",
    "            \"\"\",\n",
    "            unsafe_allow_html=True,\n",
    "        )\n",
    "\n",
    "st.markdown(\"<br>\", unsafe_allow_html=True)\n",
    "\n",
    "# =============================================================================\n",
    "# SELECCIÓN DE PLAN\n",
    "# =============================================================================\n",
    "st.markdown(\"## Elige tu plan\")\n",
    "\n",
    "plan_labels = [f\"{plan['name']} — {CURRENCY}{plan['price']:,}\" for plan in PLANS]\n",
    "selected_label = st.radio(\n",
    "    \"Selecciona el plan que quieres cotizar:\",\n",
    "    options=plan_labels,\n",
    "    index=1,  # Web Profesional preseleccionado por ser el más elegido\n",
    ")\n",
    "selected_plan = PLANS[plan_labels.index(selected_label)]\n",
    "\n",
    "st.markdown(\"<br>\", unsafe_allow_html=True)\n",
    "\n",
    "# =============================================================================\n",
    "# DATOS DE CONTACTO DEL CLIENTE (opcional, se incluyen en el mensaje)\n",
    "# =============================================================================\n",
    "st.markdown(\"## Tus datos\")\n",
    "st.markdown(\n",
    "    '<p class=\"subtle-text\">Estos datos son opcionales, pero nos ayudan a atenderte más rápido.</p>',\n",
    "    unsafe_allow_html=True,\n",
    ")\n",
    "\n",
    "contact_col1, contact_col2 = st.columns(2)\n",
    "with contact_col1:\n",
    "    client_name = st.text_input(\"Nombre\", placeholder=\"Tu nombre\")\n",
    "with contact_col2:\n",
    "    client_business = st.text_input(\"Nombre de tu negocio (opcional)\", placeholder=\"Ej. Panadería Don José\")\n",
    "\n",
    "client_notes = st.text_area(\n",
    "    \"¿Algo más que debamos saber? (opcional)\",\n",
    "    placeholder=\"Ej. Necesito el sitio en español e inglés...\",\n",
    ")\n",
    "\n",
    "st.markdown(\"<br>\", unsafe_allow_html=True)\n",
    "\n",
    "# =============================================================================\n",
    "# RESUMEN Y COTIZACIÓN\n",
    "# =============================================================================\n",
    "st.markdown(\"## Resumen de tu cotización\")\n",
    "\n",
    "st.markdown(\n",
    "    f\"\"\"\n",
    "    <div class=\"quote-box\">\n",
    "        <h3>{selected_plan['name']}</h3>\n",
    "        <p class=\"subtle-text\">{selected_plan['tagline']}</p>\n",
    "        <div class=\"quote-total\">{CURRENCY}{selected_plan['price']:,}</div>\n",
    "    </div>\n",
    "    \"\"\",\n",
    "    unsafe_allow_html=True,\n",
    ")\n",
    "\n",
    "\n",
    "def build_whatsapp_message(plan: dict, name: str, business: str, notes: str) -> str:\n",
    "    \"\"\"Arma el mensaje de cotización que se enviará por WhatsApp.\"\"\"\n",
    "    greeting_name = name.strip() if name.strip() else \"un cliente interesado\"\n",
    "    lines = [\n",
    "        f\"Hola {COMPANY_NAME}, soy {greeting_name}.\",\n",
    "        \"\",\n",
    "        \"Quiero solicitar una cotización con el siguiente plan:\",\n",
    "        f\"• Plan: {plan['name']}\",\n",
    "        f\"• Precio: {CURRENCY}{plan['price']:,}\",\n",
    "        f\"• Tiempo de entrega estimado: {DELIVERY_TIME}\",\n",
    "    ]\n",
    "\n",
    "    if business.strip():\n",
    "        lines.insert(1, f\"Mi negocio se llama: {business.strip()}\")\n",
    "\n",
    "    if notes.strip():\n",
    "        lines.append(\"\")\n",
    "        lines.append(f\"Notas adicionales: {notes.strip()}\")\n",
    "\n",
    "    lines.append(\"\")\n",
    "    lines.append(\"¿Podrían confirmarme disponibilidad para iniciar el proyecto?\")\n",
    "\n",
    "    return \"\\n\".join(lines)\n",
    "\n",
    "\n",
    "whatsapp_message = build_whatsapp_message(selected_plan, client_name, client_business, client_notes)\n",
    "whatsapp_url = f\"https://wa.me/{WHATSAPP_NUMBER}?text={urllib.parse.quote(whatsapp_message)}\"\n",
    "\n",
    "with st.expander(\"Ver mensaje que se enviará por WhatsApp\"):\n",
    "    st.text(whatsapp_message)\n",
    "\n",
    "st.link_button(\n",
    "    f\"📲 Solicitar cotización de {selected_plan['name']} por WhatsApp\",\n",
    "    whatsapp_url,\n",
    "    use_container_width=True,\n",
    ")\n",
    "\n",
    "# =============================================================================\n",
    "# FOOTER\n",
    "# =============================================================================\n",
    "st.markdown(\n",
    "    f\"\"\"\n",
    "    <div class=\"am-footer\">\n",
    "        © 2026 {COMPANY_NAME}. Todos los derechos reservados. · WhatsApp: +{WHATSAPP_NUMBER}\n",
    "    </div>\n",
    "    \"\"\",\n",
    "    unsafe_allow_html=True,\n",
    ")"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
